version: 1.0.{build}

build:
  publish_wap: true #pkg for web deploy
  
before_build:
  -  nuget restore src/Screenshot.sln -verbosity detailed
  
deply:
  - provider: WebDeploy
    url: http://screenshot.jetnett.com
    on:
      branch: master
